### PR TITLE
Fixes and Refactors enemies, adds idle and death animations for them.

### LINKED ISSUE #143: Fix all SFX and Music to use new Sound Interface

### PR DESCRIPTION
**Pull request by LeonardoTPereira**
Fix #143 #141 #140
Fixes bug with bombs not exploding, refactors enemy controller, adds idle and death animations for all enemies and change sword/shield enemy to new skeleton sprites. Adds animators, animations and sprites for the new animations, as well as a package which helps importing aseprites animations via .aseprite files. adds polymorphism to enemies and refactors shoot and walk functions to use co-routines instead of update loop. Adds a Color Palette SO to centralize enemy coloring. Creates scene for "arena" against enemies loaded from an EnemySO Dictionary. Some small refactorings related to enemy loading and processing.

### CODE REVIEW

File: Assets/Scripts/Game/EnemyManager/MageController.cs [hunk 1]
```diff
@@ -0,0 +1,108 @@
...
+                    SetColors(enemyColorPalette.MainColorB, enemyColorPalette.DetailColorB);
+
+                }
+            }
+            else
+            {
+                SetColors(enemyColorPalette.MainColorC, enemyColorPalette.DetailColorC);
+            }
+            CooldownTime = 1.0f / AttackSpeed;
+            ProjectileSpeed = enemyData.projectileSpeed * 4;
```
Comment (luizatvieira) [inline Assets/Scripts/Game/EnemyManager/MageController.cs:98]: It would be more intuitive if this 4 was a constant declared at the start of the class

**Review by luizatvieira — APPROVED** [review]
😄 👍
