### PR TITLE
Adds rich-text event parser for dialogues and Go-To quests now makes camera go to the desired room on minimap. Fixes item-placing bug.

### LINKED ISSUE #171: Fixes item/npc/player placing bug
Placeable elements are not being placed correctly inside rooms

### PR DESCRIPTION
**Pull request by LeonardoTPereira**
Fix #171 #173 #174 #175
Adds NPCs to arena scene. Adds a rich-text tag parser for dialogues to call events after (or before) each spoken dialogue line. Adds the TaggedDialogueHandler.cs to handle this. Adds a tag and event for opening the minimap on fullscreen mode and moving the camera to center to the rooms the player must go to in "Go To" quests. Paint the goal room of "Go To" quests in red in the minimap, if not yet visited. Fixes the content spawner logic for rooms, adding a necessary offset that the dungeon room uses to place tiles. Enemies now stop their coroutines when dying, making them not move while death animation is playing. Makes QuestUI.cs receive reference of input action, as the other way with the whole input was causing a conflict between actions in the dungeon scene and bugging the UIs.

### CODE REVIEW

File: Assets/Scripts/Game/LevelManager/DungeonLoader/DungeonRoom.cs [hunk 1]
```diff
@@ -58,7 +58,7 @@ public Vector3 GetNextAvailablePosition()
                 var y = candidateTile.Position.y;
                 PushNewTiles(x, y);
             } while (_floodFillState.Count > 0 && TileIsOccupied(candidateTile));
-            _currentFreeTilePosition = new Vector3(candidateTile.Position.x + 0.5f - Dimensions.Width/2, candidateTile.Position.y - 0.5f - Dimensions.Height/2, 0);
+            _currentFreeTilePosition = new Vector3(candidateTile.Position.x + 0.5f - Dimensions.Width/2,  Dimensions.Height -1 - candidateTile.Position.y + 0.5f - Dimensions.Height/2, 0);
```
Comment (luizatvieira) [inline Assets/Scripts/Game/LevelManager/DungeonLoader/DungeonRoom.cs:61]: This line is a bit hard to understand in the first look, it has a lot of numbers and calculations that I wouldn't understand without asking you. Therefore, I would create little function calls to make it a little bit more clear. For example:

GetXTilePosition( candidateTile.Position.x), in which you would return:  candidateTile.Position.x + 0.5f - Dimensions.Width/2
And
GetYTilePosition(candidateTile.Position.y), in which you would return:  Dimensions.Height -1 - candidateTile.Position.y + 0.5f - Dimensions.Height/2

Or just GetTilePosition(candidateTile.Position);

**Review by luizatvieira — APPROVED** [review]
😄 👍
